/**
 * hub.js - Server Hub menu (custom). Generated by claude/shop-data/gen_shops.py.
 * Opened by @menu (MenuCommand.java) via openNpc(9201051, "hub"): always shows the hub.
 * Two levels: Commands (info) + Shops (openShopNPC). GM Shop shows only to GMs.
 * Shop ids 7000100-7000700 come from Flyway V1.11.6/V1.11.7. See claude/NPCS-CRIADOS.md (#4).
 */

var COMMANDS = [
    ["@taxi", "Free teleport to every main town"],
    ["@reborn", "Rebirth at max level (back to Beginner, +1 reborn)"],
    ["@jobup", "Job advancement, 1st through 4th"],
    ["@salon", "Change hair, face, skin tone and colors"],
    ["@teleport", "Warp to bosses, level maps, towns and events"],
    ["@learnskill", "Learn Double Jump (-) and Teleport (+)"],
    ["@maxskills", "Max every skill for your current job (no books)"],
    ["@newbiegift", "One-time starter gift"],
    ["@checkin", "Daily check-in reward"],
    ["@onlinereward", "Reward for time spent online"],
    ["@mapdrops", "See what the current map drops"],
    ["@deleteitems", "Clean out an inventory tab"]
];

var CATS = [
    ["Weapons & Class Gear", [["Warrior Gear I", 7000100, 300], ["Warrior Gear II", 7000101, 300], ["Warrior Gear III", 7000102, 231], ["Magician Gear I", 7000103, 300], ["Magician Gear II", 7000104, 109], ["Bowman Gear I", 7000105, 300], ["Bowman Gear II", 7000106, 119], ["Thief Gear I", 7000107, 300], ["Thief Gear II", 7000108, 211], ["Pirate Gear", 7000109, 142]]],
    ["Armor & Accessories", [["Hats I", 7000200, 300], ["Hats II", 7000201, 300], ["Hats III", 7000202, 36], ["Tops I", 7000203, 300], ["Tops II", 7000204, 263], ["Bottoms", 7000205, 209], ["Shoes", 7000206, 198], ["Gloves", 7000207, 62], ["Shields", 7000208, 16], ["Capes", 7000209, 177], ["Accessories I", 7000210, 300], ["Accessories II", 7000211, 300], ["Accessories III", 7000212, 9]]],
    ["Consumables", [["Potions", 7000300, 55], ["Scrolls I", 7000301, 300], ["Scrolls II", 7000302, 300], ["Scrolls III", 7000303, 154], ["Food & Buffs I", 7000304, 300], ["Food & Buffs II", 7000305, 222], ["Ammo", 7000306, 29], ["Misc Use I", 7000307, 300], ["Misc Use II", 7000308, 300], ["Misc Use III", 7000309, 300], ["Misc Use IV", 7000310, 30]]],
    ["Setup", [["Setup Furniture", 7000400, 294]]],
    ["Etc", [["Crafting", 7000500, 117], ["Books & Guides", 7000501, 91], ["Minerals & Gems", 7000502, 38], ["Minigame", 7000503, 30], ["Misc Etc", 7000504, 150]]],
    ["Boss Drops", [["Boss Equipment", 7000600, 89]]],
    ["Anniversary & Maple", [["Anniversary & Maple Gear", 7000700, 154]]]
];

var stage = 0;
var cat = -1;

function hubMain() {
    var t = "#e#rServer Hub#k#n\r\n";
    t += "Click a #bcommand#k for info, or a #bshop#k to browse.\r\n";
    var i = 0;
    t += "\r\n#r#eCommands#k#n\r\n";
    for (var c = 0; c < COMMANDS.length; c++) {
        t += "#L" + i + "##b" + COMMANDS[c][0] + "#k#l\r\n";
        i++;
    }
    t += "\r\n#r#eShops#k#n\r\n";
    for (var s = 0; s < CATS.length; s++) {
        t += "#L" + i + "##b" + CATS[s][0] + "#k#l\r\n";
        i++;
    }
    if (cm.getPlayer().isGM()) {
        t += "\r\n#r#eGM#k#n\r\n";
        t += "#L" + i + "##bGM Shop#k#l\r\n";
    }
    cm.sendSimple(t);
}

function hubOnMain(selection) {
    var nc = COMMANDS.length;
    var ncat = CATS.length;
    if (selection < nc) {
        cm.sendOk("#e#r" + COMMANDS[selection][0] + "#k#n\r\n\r\n" + COMMANDS[selection][1]
                  + "\r\n\r\nType #b" + COMMANDS[selection][0] + "#k in the chat to use it.");
        cm.dispose();
    } else if (selection < nc + ncat) {
        cat = selection - nc;
        stage = 1;
        hubCat();
    } else {
        cm.openShopNPC(1337);   // GM Shop (GMs only)
        cm.dispose();
    }
}

function hubCat() {
    var shops = CATS[cat][1];
    var t = "#e#r" + CATS[cat][0] + "#k#n\r\n\r\n";
    for (var i = 0; i < shops.length; i++) {
        t += "#L" + i + "##b" + shops[i][0] + "#k#l #r(" + shops[i][2] + " items)#k\r\n";
    }
    cm.sendSimple(t);
}

function hubOnCat(selection) {
    var shops = CATS[cat][1];
    if (selection >= 0 && selection < shops.length) {
        cm.openShopNPC(shops[selection][1]);
    }
    cm.dispose();
}

function start() {
    stage = 0;
    hubMain();
}

function action(mode, type, selection) {
    if (mode != 1) { cm.dispose(); return; }
    if (stage == 0) { hubOnMain(selection); } else { hubOnCat(selection); }
}
